import 'package:flutter/material.dart';

const primaryColor = Color(0xFF2697FF);
const secondaryColor = Color(0xFF2A2D3E);
const bgColor = Color(0xFF212332);

const defaultPadding = 16.0;

const positiveSentiments = ['Sustainable', 'Effective', 'Appreciate', 'Producing', 'Hopeful', 'Engagement', 'Patience', 'Bright', 'Practical', 'Reenabled', 'Inform', 'Creating', 'Compelling', 'Engineering', 'Aiming', 'Freedom', 'Controls', 'Collaboration', 'Amazingly', 'Optimize', 'Addressed', 'Envision', 'Promised', 'Surprise', 'Reusable', 'Realizing', 'Protecting', 'Improved', 'Entertain', 'Amused', 'Enduring', 'Admire', 'Laugh', 'Delightful', 'Like', 'Immediately', 'Fixing', 'Debugging', 'Engaging', 'Contributions', 'Cooperative', 'Neuralink', 'Oversubscribed', 'Comforting', 'Peaceful', 'Endorse', 'Educational', 'Getting ready for the game and feeling optimistic', 'Curious', 'Improve', 'Funny', 'Adapting', 'Aspire', 'Fascinate', 'Follow', 'Bought', 'Enjoying', 'Investing', 'Thanks', 'Supporting', 'Subscribe', 'Approving', 'Celebratory', 'Secure', 'Refreshing', 'Cool', 'Welcome', 'Appreciated', 'Approved', 'Accepting', 'Aligned', 'Moderation', 'Networking', 'Prosperous', 'Glorious', 'Invested', 'Refine', 'Congratulations', 'Collaborating', 'Growing', 'Brave', 'Epic', 'Succeed', 'Approval'];
const negativeSentiments = ["Problematic", "Disingenuous", "Trouble", "Opinionated", "Wary", "Disappointment", "Worried", "Threaten", "Corrected", "Silly", "Avoid", "Moderate", "Limited", "Corrupt", "Delayed", "Racist", "Disgruntled", "Close", "Incorrect", "Stakes", "Fight", "RIP", "Questionable", "Defunded", "Conspiracies", "Stasi", "Disrespect", "Misled", "Grumpy", "Careful", "Stretch", "Late", "Crisis", "Frustration", "Yikes", "Reduction", "Illegally", "Suspension", "Embarrassing", "Fraudulent", "Escalating", "Imperfect", "Violate", "Tired", "Scolding", "Disturbing", "Resentful", "Disagree", "Negatively", "Dismissed", "Criminalize", "Disgraceful", "Dropped"];
const neutralSentiments = ["Investigating", "Disingenuous", "Avoid", "Limited", "Inform", "Delayed", "Challenge", "Incorrect", "Engaging", "Late", "Cautious", "Propaganda", "Late", "Difficult", "Dire", "Generosity", "Condemning", "Reduce", "Missed", "Opposition", "Stop", "Oversubscribed", "Questionable", "Peaceful", "Listen", "Changes", "Educational", "Curious", "Late", "Defend", "Reduction", "Thanks", "Suspension", "Embarrassing", "Fraudulent", "Celebratory", "Shorten", "Charge", "Trying", "Condemn", "Nostalgia", "Proposal", "Reminds", "Anticipating", "Responsible", "Attack", "Unfortunate", "Surprised", "Competitive", "Decide", "Negatively", "Replace", "Nostalgic", "Anger", "Approval"];

